spring:
  application:
    name: auth-service
security:
  jwt:
    token:
      secret-key: hjf203cupnacs2039r1mjkc1ascdjkfkds9sdnfasb8ica1
      expire-length: PT30M
redis:
  host: localhost
  port: 6379
