services:
  database:
    container_name: pg-database
    image: postgres:16.2
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: cupid-meet
    ports:
      - "5433:5432"
    networks:
      - cupid-network

  user-details-service:
    image: qaaaaisar04/user-details-service
    container_name: user-details-service
    depends_on:
      - database
    ports:
      - "8728:8728"
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: cupid-meet
      DB_USER: postgres
      DB_PASSWORD: postgres
    restart: always
    networks:
      - cupid-network

  location-data-service:
    image: qaaaaisar04/location-data-service
    container_name: location-data-service
    ports:
      - "8580:8580"
    environment:
      LOCATIONIQ_API_KEY:
    restart: always
    networks:
      - cupid-network

  user-matching-service:
    image: qaaaaisar04/user-matching-service
    container_name: user-matching-service
    depends_on:
      - database
    ports:
      - "8146:8146"
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: cupid-meet
      DB_USER: postgres
      DB_PASSWORD: postgres
    restart: always
    networks:
      - cupid-network

  feedback-service:
    image: qaaaaisar04/feedback-service
    container_name: feedback-service
    depends_on:
      - database
    ports:
      - "8504:8504"
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: cupid-meet
      DB_USER: postgres
      DB_PASSWORD: postgres
    restart: always
    networks:
      - cupid-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/qaisar.online/fullchain.pem:/etc/nginx/certs/fullchain.pem
      - /etc/letsencrypt/live/qaisar.online/privkey.pem:/etc/nginx/certs/privkey.pem
    depends_on:
      - location-data-service
      - user-details-service
      - feedback-service
    networks:
      - cupid-network

volumes:
  minio_data:

networks:
  cupid-network: