services:
  database:
    container_name: pg-database
    image: postgres:16.2
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: cupid-meet
    ports:
      - "5433:5432"
    networks:
      - cupid-network

  user-details-service:
    image: qaaaaisar04/user-details-service
    container_name: user-details-service
    depends_on:
      - database
    ports:
      - "8728:8728"
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: cupid-meet
      DB_USER: postgres
      DB_PASSWORD: postgres
    restart: always
    networks:
      - cupid-network

  location-data-service:
    image: qaaaaisar04/location-data-service
    container_name: location-data-service
    ports:
      - "8580:8580"
    environment:
      LOCATIONIQ_API_KEY: pk.d2903abe53c3326c6c3ec87ca2ead0de
    restart: always
    networks:
      - cupid-network

  feedback-service:
    image: qaaaaisar04/feedback-service
    container_name: feedback-service
    depends_on:
      - database
    ports:
      - "8504:8504"
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: cupid-meet
      DB_USER: postgres
      DB_PASSWORD: postgres
    restart: always
    networks:
      - cupid-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/qaisar.online/fullchain.pem:/etc/nginx/certs/fullchain.pem
      - /etc/letsencrypt/live/qaisar.online/privkey.pem:/etc/nginx/certs/privkey.pem
    depends_on:
      - location-data-service
      - user-details-service
      - feedback-service
    networks:
      - cupid-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - cupid-network

  telegram-bot:
    image: qaaaaisar04/cupidmeet-telegram-bot:v1.11
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - TOKEN=7411579054:AAGJiFtdlJ7PGSw2dFsDjI14EvK94rF0QwY
      - API_URL=http://user-details-service:8728/api/v1
      - LOCATION_DATA_API=http://location-data-service:8580/api/v1/maps
    command: python start.py
    depends_on:
      - redis
      - database
      - user-details-service
      - location-data-service
    networks:
      - cupid-network

volumes:
  minio_data:

networks:
  cupid-network: