services:
  database:
    container_name: pg-database
    image: postgres:16.2
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: cupid-meet
    ports:
      - "5433:5432"
    networks:
      - cupid-network

  minio:
    image: minio/minio:RELEASE.2024-05-10T01-41-38Z-cpuv1
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    volumes:
      - minio_data:/data
    command: server /data
    networks:
      - cupid-network

  minio-config:
    image: minio/mc
    depends_on:
      - minio
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    entrypoint: [ "sh", "-c",
      "mc alias set cupidmeet http://minio:9000 ${MINIO_ACCESS_KEY:-minioadmin} ${MINIO_SECRET_KEY:-minioadmin} 
      && mc mb cupidmeet/cupid-meet" ]
    networks:
      - cupid-network

  storage-service:
    image: qaaaaisar04/storage-service
    container_name: storage-service
    depends_on:
      - minio-config
      - database
    ports:
      - "8084:8084"
    environment:
      S3_ENDPOINT: http://minio:9000
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: cupid-meet
      DB_USER: postgres
      DB_PASSWORD: postgres
    restart: always
    networks:
      - cupid-network

  user-details-service:
    image: qaaaaisar04/user-details-service
    container_name: user-details-service
    depends_on:
      - database
      - storage-service
    ports:
      - "8728:8728"
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: cupid-meet
      DB_USER: postgres
      DB_PASSWORD: postgres
    restart: always
    networks:
      - cupid-network

  location-data-service:
    image: qaaaaisar04/location-data-service
    container_name: location-data-service
    ports:
      - "8580:8580"
    environment:
      LOCATIONIQ_API_KEY: pk:e7adea0216da76d494f2416952b8527d
    restart: always
    networks:
      - cupid-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/qaisar.online/:/etc/nginx/certs
    depends_on:
      - storage-service
      - location-data-service
      - user-details-service
    networks:
      - cupid-network

volumes:
  minio_data:

networks:
  cupid-network: