spring:
  application:
    name: user-matching-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:cupid-meet}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    default-schema: matching_service
    liquibase-schema: develop
    change-log: db/changelog/changelog.xml
    drop-first: true
  jpa:
    hibernate:
      ddl-auto: validate
springdoc:
  api-docs:
    enabled: true
    path: /user-matching-service/doc/json
  swagger-ui:
    path: /user-matching-service/doc
server:
  port: 8146