global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'user_details_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'user-details-service:8090' ]
        labels:
          application: 'User Details Service Application'