server:
  servlet:
    context-path: /api/qr-service
  port: 7070
  forward-headers-strategy: framework

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_URI:https://qaisar.online:8843/realms/cupid-meet-dev/protocol/openid-connect/certs}
  application:
    name: qr-service

qr:
  width: 600
  height: 600
  charset: UTF-8

management:
  server:
    port: 8090
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health, info, prometheus, loggers

grpc:
  client:
    qrCodeService:
      address: ${STORAGE_SERVICE_GRPC_URL:localhost:8801}
      negotiation-type: plaintext

application:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}

keycloak:
  auth-server-url: ${KEYCLOAK_SERVER_URL:https://qaisar.online:8843/auth}
  realm: ${KEYCLOAK_REALM:cupid-meet-dev}
  resource: ${KEYCLOAK_CLIENT:cupid-meet-dev}
  bearer-only: true
