spring:
  application:
    name: qr-service

qr:
  width: 600
  height: 600
  charset: UTF-8

springdoc:
  api-docs:
    enabled: true
    path: /qr-service/doc/json
  swagger-ui:
    path: /qr-service/doc

grpc:
  client:
    qrCodeService:
      address: ${STORAGE_SERVICE_GRPC_URL:localhost:8801}
      negotiation-type: plaintext

server:
  port: 7070