spring:
  application:
    name: telegram-bot-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:cupid-meet}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
redis:
  host: localhost
  port: 6379
bot:
  token:
    api: ${BOT_TOKEN:7411579054:AAGJiFtdlJ7PGSw2dFsDjI14EvK94rF0QwY}