spring:
  application:
    name: user-details-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:qaisar.online}:${DB_PORT:5433}/${DB_NAME:cupid-meet}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/changelog/changelog.xml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

application:
  user:
    history:
      cleanup:
        reprocess-delayed-cron: 0 0 0 1 * ?
        scheduler:
          enabled: true

springdoc:
  api-docs:
    enabled: true
    path: /user-details-service/doc/json
  swagger-ui:
    path: /user-details-service/doc

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
server:
  port: 8728
  forward-headers-strategy: framework