spring:
  application:
    name: user-details-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:cupid-meet}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    default-schema: user_detail
    liquibase-schema: develop
    change-log: db/changelog/changelog.xml
    drop-first: false
  jpa:
    hibernate:
      ddl-auto: validate
springdoc:
  api-docs:
    enabled: true
    path: /user-details-service/doc/json
  swagger-ui:
    path: /user-details-service/doc
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
server:
  port: 8728
  forward-headers-strategy: framework