spring:
  application:
    name: user-details-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:cupid-meet}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    default-schema: telegram
    liquibase-schema: develop
    change-log: db/changelog/changelog.xml
  jpa:
    hibernate:
      ddl-auto: validate