spring:
  application:
    name: storage-service
  cloud:
    aws:
      region:
        static: 'null'
      credentials:
        access-key: ${S3_ACCESS_KEY:minioadmin}
        secret-key: ${S3_SECRET_KEY:minioadmin}
      s3:
        path-style-access-enabled: true
        endpoint: ${S3_ENDPOINT:http://localhost:9000}
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:cupid-meet}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    default-schema: storage
    liquibase-schema: develop
    change-log: db/changelog/changelog.xml
    drop-first: true
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_REQUEST_SIZE:10MB}
minio:
  environment:
    bucket-name: ${MINIO_BUCKET_NAME:cupid-meet}
contentDisposition: attachment
server:
  port: 8084
scheduler:
  cron: 0 0 0 * * MON