spring:
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5433/postgres
    driver-class-name: org.postgresql.Driver
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  application:
    name: storage-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 0
