spring:
  application:
    name: location-data-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
springdoc:
  api-docs:
    enabled: true
    path: /swagger-ui.html
locationiq:
  api-key: ${LOCATIONIQ_API_KEY}