spring:
  application:
    name: location-data-service

springdoc:
  api-docs:
    enabled: true
    path: /location-data-service/doc/json
  swagger-ui:
    path: /location-data-service/doc

locationiq:
  api-key: ${LOCATIONIQ_API_KEY}

management:
  server:
    port: 8090
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health, info, prometheus, loggers

server:
  port: 8580
  forward-headers-strategy: framework