spring:
  application:
    name: location-data-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://${KEYCLOAK_HOST:qaisar:online:8843}/realms/cupid-meet-dev/protocol/openid-connect/certs

springdoc:
  api-docs:
    enabled: true
    path: /location-data-service/doc/json
  swagger-ui:
    path: /location-data-service/doc

locationiq:
  api-key: ${LOCATIONIQ_API_KEY}

server:
  port: 8580
  forward-headers-strategy: framework