apiVersion: apps/v1
kind: Deployment
metadata:
  name: qr-config-server-deployment
  labels:
    app: qr-config-server
spec:
  selector:
    matchLabels:
      app: qr-config-server
  template:
    metadata:
      labels:
        app: qr-config-server
    spec:
      containers:
        - name: qr-service
          image: qaaaaisar04/qr-service
          ports:
            - containerPort: 8728
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: git
---
apiVersion: v1
kind: Service
metadata:
  name: qr-config-server-svc
spec:
  type: NodePort
  ports:
    - port: 8888
      name: http
  selector:
    app: qr-config-server
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qr-config-server-ingress
spec:
  rules:
    - host: config.qr
      http:
        paths:
          - path: /
            pathType: prefix
            backend:
              service:
                name: qr-config-server-svc
                port:
                  name: http
