spring:
  application:
    name: feedback-service
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml
    liquibase-schema: develop
    default-schema: feedback
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:cupid-meet}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
springdoc:
  api-docs:
    enabled: true
    path: /feedback-service/doc/json
  swagger-ui:
    path: /feedback-service/doc
