spring:
  application:
    name: feedback-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:qaisar.online}:${DB_PORT:5433}/${DB_NAME:cupid-meet}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate

springdoc:
  api-docs:
    enabled: true
    path: /feedback-service/doc/json
  swagger-ui:
    path: /feedback-service/doc

server:
  port: 8504
  forward-headers-strategy: framework