spring:
  application:
    name: feedback-service
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml
    liquibase-schema: develop
    default-schema: feedback

  datasource:
    url: jdbc:postgresql://localhost:5433/cupid-meet
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

