name: CI/CD User Matching Service

on:
  push:
    branches:
      - main
    paths:
      - 'user-matching-service/**'

jobs:
  build-and-deploy:
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository user matching service
        uses: actions/checkout@v3

      - name: Set up jdk 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push docker image
        run: |
          cd user-matching-service
          mvn compile jib:build  -DskipTests\
            -Djib.to.auth.username=$DOCKER_USERNAME\
            -Djib.to.auth.password=$DOCKER_PASSWORD\
            -Djib.to.platform=linux/amd64,linux/arm64